import AddForm from "./AddForm";

export const metadata = {
  title: "Add Feedback",
  description: "Generated by create next app",
};

const AddFeedback = () => {
  return (
    <div className=" text-center space-y-5">
      <h1 className="text-2xl font-bold">Add your valuable feedback.</h1>
      <AddForm></AddForm>
    </div>
  );
};

export default AddFeedback;
