import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import FoodCardContext from "../context/FoodCardContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between px-4 py-2">
          <Link
            href={"/"}
            className="text-xl font-semibold p-2 text-cyan-500 border-2 rounded italic animate-pulse"
          >
            Food-Lover
          </Link>
          <nav className="space-x-4">
            <Link
              href={"/foods"}
              className="border-cyan-500 rounded hover:bg-cyan-700 hover:text-white px-4 py-2 transition-all duration-300 border"
            >
              Foods
            </Link>
            <Link
              href={"/reviews"}
              className="border-cyan-500 rounded hover:bg-cyan-700 hover:text-white px-4 py-2 transition-all duration-300 border"
            >
              Reviews
            </Link>
          </nav>
        </header>
        <main className="px-6 py-2">
          <FoodCardContext>{children}</FoodCardContext>
        </main>
      </body>
    </html>
  );
}
